### ISSUE TITLE
Remove access to org.gnome.SettingsDaemon

### ISSUE THREAD

**Issue by hadess** [flathub/com.googleplaymusicdesktopplayer.GPMDP#10]
The correct D-Bus name is `org.gnome.SettingsDaemon.MediaKeys`, and host implementations should be fixed instead of allowing access to a potentially dangerous daemon. See:
https://bugzilla.gnome.org/show_bug.cgi?id=781326#c8

**Comment by TingPing** [comment]
Reported upstream: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2864

**Comment by TingPing** [comment]
Permission removed anyway since it doesn't do anything, but the actual fix is on upstream.
