### ISSUE TITLE
Flatpak GPMDP consumes too much CPU

### ISSUE THREAD

**Issue by aldevel** [flathub/com.googleplaymusicdesktopplayer.GPMDP#13]
Hello,
I'd like to report this issue directly related to given bug of the main application and ask to upgrade flathub/com.googleplaymusicdesktopplayer.GPMDP to the version of the main application where this issue most likely solved as soon as possible because this amount of CPU usage isn't normal. 
Related bug:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3332
I understand it's not a simple upgrade but a time consuming work to pack the original one into Flatpak and also this issue is not yet solved entirely, not even in the original one, I noted this for follow up only.
Thank you!

**Comment by TingPing** [comment]
This already has the latest release and that issue was never closed upstream so probably not fixed.

**Comment by aldevel** [comment]
Wow, good to know it's the latest release. Yes it's not fixed probably. If it wasn't right to opening this report for Flathub version from several aspects than I'm sorry and please close it if you don't see this issue as directly related one to flathub/com.googleplaymusicdesktopplayer.GPMDP.

**Comment by TingPing** [comment]
Yes I think the upstream issue is an indication its not a package problem.
