### ISSUE TITLE
System Tray Icon doesn't show

### ISSUE THREAD

**Issue by mkeedlinger** [flathub/com.googleplaymusicdesktopplayer.GPMDP#14]
I'm on Ubuntu 18.10, all updated software. Since the indicator doesn't show, you have to make sure that the "minimize to tray" setting isn't checked otherwise when closing the window, it hides and cannot easily be unhidden (if you start the application again, it does unhide).

<sub><sub>Thanks for all the work on this flatpak, I love using it!</sub></sub>

**Comment by Cyvain87** [comment]
I am having the same issue with the app indicator not showing up on fedora as well. This is a problem as YouTube music cannot be accessed in the app without the indicator.

**Comment by razzeee** [comment]
Seeing the same on fedora 33

**Comment by razzeee** [comment]
Seems like https://github.com/flathub/org.keepassxc.KeePassXC/commit/362a037832c2e653eb2bf98d75eaf352c17ca3c3 might be a fix
