### ISSUE TITLE
update to 4.7.0 version to fix sign in issue

### ISSUE THREAD

**Issue by gonzalomarcote** [flathub/com.googleplaymusicdesktopplayer.GPMDP#16]
Due the Google Sign in bug:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545

this flatpak com.googleplaymusicdesktopplayer.GPMDP app should be updated to 4.7.0 version:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3761#issuecomment-569455691

becuase now is unusable and it is not able to login.

**Comment by TingPing** [comment]
This package needs a maintainer.

**Comment by tante** [comment]
I added a pull request with an update.

**Comment by tante** [comment]
Btw. due to a bug in the release version 4.7.1 is the current one.
