### ISSUE TITLE
Rich presence

### ISSUE THREAD

**Issue by Leeo97one** [flathub/com.googleplaymusicdesktopplayer.GPMDP#7]
How can we let this flatpak notify a Discord client about rich presence?

**Comment by TingPing** [comment]
Probably not possible but I'm not familiar with it, do you have a link to any more information?

**Comment by TingPing** [comment]
I guess this is better handled here anyway: https://github.com/flathub/com.discordapp.Discord/issues/29

**Comment by Amosar** [comment]
The flatpak version of discord now support RPC https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)
Can you support this on this flatpak please? 
You can found a WIP for steam her https://github.com/flathub/com.valvesoftware.Steam/pull/273

**Comment by TingPing** [comment]
Maybe @gasinvein can make a PR.

**Comment by gasinvein** [comment]
Done. I don't have a Play Music account, so please test this https://github.com/flathub/com.googleplaymusicdesktopplayer.GPMDP/pull/12#issuecomment-445480767 build.

**Comment by Amosar** [comment]
Thanks for you work on this support @gasinvein :)
But your patch doesn't work :/ 
The script seems to not create the simlink into the flatpak container : 
```
amosar@amosar-Fix:/run/user/1000$ flatpak run --command=/bin/bash com.googleplaymusicdesktopplayer.GPMDP/x86_64/stable
bash-4.4$ ls -l $XDG_RUNTIME_DIR/
total 4
drwxr-xr-x 3 amosar amosar 60 10 déc.  00:02 app
srwxrwxr-x 1 amosar amosar  0 10 déc.  00:02 at-spi-bus
srwxrwxr-x 1 amosar amosar  0 10 déc.  00:02 bus
drwxr-xr-x 2 amosar amosar 60  9 déc.  18:36 discord
dr-x------ 2 amosar amosar  0  1 janv.  1970 doc
lrwxrwxrwx 1 amosar amosar 22 10 déc.  00:02 flatpak-info -> ../../../.flatpak-info
drwxr-xr-x 2 amosar amosar 80 10 déc.  00:02 pulse
-rw------- 0 amosar amosar 56 10 déc.  00:02 Xauthority
bash-4.4$ ls -l $XDG_RUNTIME_DIR/discord/
total 0
srwxrwxr-x 1 amosar amosar 0  9 déc.  18:36 ipc-0
```
If I run your loop manually and then I run `gpmdp` into the container then the integration work

**Comment by gasinvein** [comment]
@Amosar 
>`flatpak run --command=/bin/bash com.googleplaymusicdesktopplayer.GPMDP/x86_64/stable`

This way the code in the wrapper script wouldn't work, because the wrapper isn't executed at all.
Run the warpper `google-play-music-desktop-player` directly from sandbox shell, or use desktop launcher.

**Comment by Amosar** [comment]
I have tried but that doesn't work, this is why I have tried to run the loop manually

**Comment by gasinvein** [comment]
That's strange. Can you please run `bash -x 
google-play-music-desktop-player` (from inside sandbox) and post output 
here?

**Comment by gasinvein** [comment]
That's strange. Can you please run `bash -x google-play-music-desktop-player` (from inside sandbox) and post output here?

**Comment by Amosar** [comment]
I have found something new when I have launch your commande, but thats weird
If I run your command directly the process number is small than 10 and discord refused to use it
But if I kill it with CTRL+C then I run your command again this work.
this one not work
![discord](https://user-images.githubusercontent.com/14032531/49763100-07409100-fccc-11e8-8022-98c004f94de5.png)

And this one work
![discord2](https://user-images.githubusercontent.com/14032531/49763107-09a2eb00-fccc-11e8-9a6e-c69be15c3591.png)

**Comment by gasinvein** [comment]
Well, does the wrapper create symlinks for you?

**Comment by Amosar** [comment]
Yes it create it because it can communicate with the discord container and `bash -x google-play-music-desktop-player` execute the loop as expected.

**Comment by nanonyme** [comment]
I suggest hunting down where that min PID assumption comes from. It's invalid for Flatpak
